services:
  - type: web
    name: lop-co-nga-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lop-co-nga-db
          property: connectionString

databases:
  - name: lop-co-nga-db
    plan: free
